#!/bin/bash
echo "// This file is automatically generated. Don't edit it."
echo "#ifndef __SYMTAB_H"
echo "#define __SYMTAB_H"
grep '                0x00000000........                ' build/link.map | \
	while read sym; do
	declare -a dat
	dat=($sym)
	offs=${dat[0]}
	name=${dat[1]}

	offs="$(echo "$offs" | sed 's|00000000||g')"

	if [ "$name" != "." ]; then
		echo "  #define ${name}_offset ((void*)${offs})"
	fi
done
echo "#endif"
